### ISSUE TITLE
Having trouble adding new tags in cloud interface

### ISSUE THREAD

**Issue by EricThomson** [mattaq31/Zotero-Report-Cleaner#2]
The report cleaner is working great, and now I'm trying to remove a few remaining items of information from my report (`Tags`, `Attachments`, `Quality report`, `Select in Zotero`).  You can see one reference here from a report:

![zotero_report_simplified](https://github.com/user-attachments/assets/5867c88d-bb01-4872-96ff-b26d477b7480)

When I enter `Tags` (or other entries) into the field, and then move them over to `Tags to Discard` they aren't being removed from the report. Not sure what I'm doing wrong.

**Comment by mattaq31** [comment]
Hi @EricThomson I didn't code in a feature to get rid of the additional elements underneath the main table (enclosed in the box).  However, I think that implementing the feature shouldn't take too much time since it basically just involves looking for the H3 headers under the table and deciding on whether they should be removed.  I can look into this later this week or alternatively you're welcome to add the feature yourself!

**Comment by EricThomson** [comment]
Ok thanks I'll check it out.

**Comment by EricThomson** [comment]
I'm working on it now will make a PR this week

**Comment by mattaq31** [comment]
Actually I managed to find time to deal with it now - it's live on the website, check it out and let me know if it works!  (you need to first move the tags/attachments/qualityReport nodes to the 'tags to discard' table first)

**Comment by EricThomson** [comment]
Cool thanks! Will check it out 😄 

Note while messing around with the cli I did have to change a couple of things to get it working with Windows, I'm not sure if it is worth worrying about (I use Linux, but ... I often test things on Windows too). 

Line 50 of `html_manipulator.py` I had to change to:

`        with open(self.output_dir, "w", encoding="utf-8") as file:`

And line 35 I had to change to:

`        self.parse_html(open(input_loc, "rb"))`

I'm not sure if this would mess encodings up in Linux is the problem. 🤷 

At any rate cli is working and was about to start making lists of h3 items. But it seems you already did thanks a lot!!!

**Comment by EricThomson** [comment]
Yep works great, thanks again!

**Comment by mattaq31** [comment]
@EricThomson  I tested both lines you suggested and they still work ok on Mac - so feel free to generate a PR to make the package work on Windows!  Thanks for going through everything!

**Comment by EricThomson** [comment]
Ok great will do!
